# Generated by Django 5.2 on 2025-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=100)),
                ('plataforma', models.CharField(choices=[('TECNO', 'Tecnoempleo'), ('INFO', 'InfoJobs'), ('LINKED', 'LinkedIn')], max_length=6)),
                ('salario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateField()),
                ('url', models.URLField(max_length=500)),
                ('habilidades', models.ManyToManyField(to='datos.habilidad')),
            ],
            options={
                'verbose_name_plural': 'Ofertas de empleo',
                'ordering': ['-fecha_publicacion'],
                'indexes': [models.Index(fields=['plataforma'], name='datos_ofert_platafo_491869_idx'), models.Index(fields=['empresa'], name='datos_ofert_empresa_f137f7_idx'), models.Index(fields=['ubicacion'], name='datos_ofert_ubicaci_9b7b59_idx')],
            },
        ),
    ]
