# Generated by Django 5.2 on 2025-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PLAN', 'Planeación'), ('ACT', 'En Progreso'), ('SUSP', 'Suspendido'), ('COMP', 'Completado')], default='PLAN', max_length=4)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PROG', 'En Progreso'), ('COMP', 'Completada')], default='PEND', max_length=4)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
