# Generated by Django 5.2 on 2025-04-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(related_name='proyectos_asignados', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='asignados',
            field=models.ManyToManyField(related_name='tareas_asignadas', to='usuarios.userprofile'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado'], name='proyectos_p_estado_fd8518_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['fecha_limite'], name='proyectos_p_fecha_l_060bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['estado'], name='proyectos_t_estado_d1afc3_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha_limite'], name='proyectos_t_fecha_l_e571a8_idx'),
        ),
    ]
